<a href="https://colab.research.google.com/github/Tikhon-Radkevich/NumPy/blob/main/NumPyGetStarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

print(np.__version__)

1.21.6


## sum

In [9]:
a = np.array(
    [[1, 2, 3], [4, 5, 6]]
)
b = np.array(
    [[10, 20, 30], [40, 50, 60]]
)

c = a + b
print(c)

[[11 22 33]
 [44 55 66]]


## Multiplying by scalar

In [7]:
double_a = a * 2
print(double_a)

[[ 2  4  6]
 [ 8 10 12]]


## Identity Matrix

In [15]:
ones = np.ones((4, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
arr = np.eye(N=4, M=4, k=-1, dtype=int)
print(arr)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


##  1-D to 3-D

In [22]:
one_d = np.array([i for i in range(27)])

three_d = one_d.reshape(3, 3, 3)
print(three_d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## elements from float to int

In [26]:
d = np.array([1.3, 2.7, 8.0])

new_d = d.astype("int")
print(new_d)

[1 2 8]


## Convert binary to boolean 

In [30]:
i = np.array([0, 1, 1, 1, 0, 0, 1, 0])

i = i.reshape(-1, 2)

new_i = i.astype("bool")
print(new_i)

[[False  True]
 [ True  True]
 [False False]
 [ True False]]


## stacking

In [37]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

hstack = np.hstack((a1, a2))
vstack = np.vstack((a1, a2))
print(hstack, vstack, sep="\n"*2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Generation

In [38]:
f = np.arange(0, 101, 5)
print(f)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


## same idexes

In [40]:
g = np.array([1,2,3,4,5])

h = np.array([1,3,2,4,5])

print(np.where(g == h))

(array([0, 3, 4]),)


## linspace

In [67]:
print(np.linspace([[0, 10], [30, 40]], [[10, 20], [40, 50]], 5, dtype=int, axis=0))

[[[ 0 10]
  [30 40]]

 [[ 2 12]
  [32 42]]

 [[ 5 15]
  [35 45]]

 [[ 7 17]
  [37 47]]

 [[10 20]
  [40 50]]]


In [68]:
print(np.linspace([[0, 10], [30, 40]], [[10, 20], [40, 50]], 5, dtype=int, axis=1))

[[[ 0 10]
  [ 2 12]
  [ 5 15]
  [ 7 17]
  [10 20]]

 [[30 40]
  [32 42]
  [35 45]
  [37 47]
  [40 50]]]


In [69]:
print(np.linspace([[0, 10], [30, 40]], [[10, 20], [40, 50]], 5, dtype=int, axis=2))

[[[ 0  2  5  7 10]
  [10 12 15 17 20]]

 [[30 32 35 37 40]
  [40 42 45 47 50]]]


## with one particular value

In [70]:
print(np.full((3, 5), 7))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
