In [1]:
import numpy as np

a = np.arange(0, 27)
a = a.reshape(3, 3, 3)

b = np.arange(10, 37)
b = b.reshape(3, 3, 3)

In [ ]:
print(a, b, sep="\n"*3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


## sum

In [ ]:
np.sum(a, axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [ ]:
np.sum(a, axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

## multiplication

In [ ]:
np.dot(np.array([1, 5]), np.array([3, 8]))

43

## Write a NumPy program to add a vector to each row of a given matrix

In [ ]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


## Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it

In [ ]:
import os
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


## Write a NumPy program to save a given array to a text file and load it.

In [ ]:
from numpy.core.fromnumeric import ndim
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt', dtype=int)
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.



In [2]:
arr_a = np.arange(16, dtype=int).reshape(4, 4)

arr_a[[0, -1], :] = arr_a[[-1, 0], :]
print(arr_a)

[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


## Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [10]:
arr_b = np.random.choice(10, 12).reshape(2, -1)

In [7]:
arr_b

array([[2, 4, 2, 8, 9, 5],
       [9, 1, 6, 6, 4, 2]])

In [12]:
print(arr_b[arr_b > 5])
print(arr_b[arr_b < 3])

[9 8 8]
[0 2 2 2 0]


## Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.

In [13]:
arr_c = np.random.choice(10, 12).reshape(2, -1)
arr_c

array([[1, 6, 9, 2, 5, 5],
       [2, 7, 7, 0, 9, 2]])

In [20]:
n = 7
r = 18
print("\nReplace elements of the said array which are equal to ",n,"with",r)
print(np.where(arr_c == n, r, arr_c))
print("\nReplace elements with of the said array which are less than",n,"with",r)
print(np.where(arr_c < n, r, arr_c))
print("\nReplace elements with of the said array which are greater than",n,"with",r)
print(np.where(arr_c > n, r, arr_c))


Replace elements of the said array which are equal to  5 with 18
[[18 18 18 18  5  5]
 [18 18 18 18 18 18]]

Replace elements with of the said array which are less than 5 with 18
[[18  6  9 18  5  5]
 [18  7  7 18  9 18]]

Replace elements with of the said array which are greater than 5 with 18
[[ 1 18 18  2  5  5]
 [ 2 18 18  0 18  2]]


In [32]:
print(np.where(arr_c > 6, False, np.ones(12, dtype=bool).reshape(2, -1)))


[[ True  True False  True  True  True]
 [ True False False  True False  True]]


## Write a NumPy program to create an array of equal shape and data type of a given array.

In [34]:
print(np.zeros_like(arr_c))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]


## Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, second and third columns


In [40]:
arr_d = np.arange(16, dtype=int).reshape(4, 4)
new_arr = np.ones_like(arr_d)

new_arr[:, [0, -1]] = arr_d[:, [-1, 0]]
new_arr[:, [1, 2]] = arr_d[:, [2, 1]]

new_arr

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [38]:
print(arr_d[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


## Write a NumPy program to swap rows and columns of a given array in reverse order

In [41]:
arr_d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
new_d = np.zeros_like(arr_d)
new_d[:, :] = arr_d[::-1, ::-1]

new_d

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

## Write a NumPy program to multiply two given arrays of same size element-by-element.

In [50]:
arr_e = np.random.randint(0, 3, (4, 4))
arr_e

array([[1, 2, 1, 0],
       [1, 1, 1, 0],
       [1, 2, 0, 0],
       [2, 0, 2, 0]])

In [51]:
np.multiply(arr_d, arr_e)

array([[ 0,  2,  2,  0],
       [ 4,  5,  6,  0],
       [ 8, 18,  0,  0],
       [24,  0, 28,  0]])